import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Dummy MRPL Logo Base64 or we can just draw text for the logo if we don't have the image file.
// We'll use text-based header for safety, but with green corporate colors.

export const generateMRPLReport = (reportTitle: string, data: any[], columns: string[]) => {
  const doc = new jsPDF();
  
  const primaryGreen = '#14501B';
  
  // 1. Add MRPL Header
  doc.setFontSize(18);
  doc.setTextColor(primaryGreen);
  doc.setFont('helvetica', 'bold');
  doc.text('MANGALORE REFINERY AND PETROCHEMICALS LIMITED', 105, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setTextColor('#333333');
  doc.setFont('helvetica', 'normal');
  doc.text('(A Subsidiary of Oil and Natural Gas Corporation Limited)', 105, 26, { align: 'center' });
  
  doc.setFontSize(9);
  doc.text('Kuthethoor P.O., Via Kattipalla, Mangaluru - 575 030, Karnataka.', 105, 32, { align: 'center' });
  
  doc.setDrawColor(primaryGreen);
  doc.setLineWidth(1.5);
  doc.line(14, 36, 196, 36);
  
  // 2. Add Report Title
  doc.setFontSize(14);
  doc.setTextColor(primaryGreen);
  doc.setFont('helvetica', 'bold');
  doc.text(reportTitle.toUpperCase(), 105, 46, { align: 'center' });
  
  // 3. Add Date and Metadata
  doc.setFontSize(10);
  doc.setTextColor('#000000');
  doc.setFont('helvetica', 'normal');
  const today = new Date().toLocaleDateString('en-IN');
  doc.text(`Date of Generation: ${today}`, 14, 56);
  doc.text(`Generated By: H2S Guard Enterprise System`, 14, 62);
  
  // 4. Add Data Table
  (doc as any).autoTable({
    startY: 68,
    head: [columns],
    body: data,
    theme: 'grid',
    headStyles: {
      fillColor: primaryGreen,
      textColor: '#FFFFFF',
      fontStyle: 'bold',
      halign: 'center'
    },
    alternateRowStyles: {
      fillColor: '#F5F9F6'
    },
    styles: {
      fontSize: 9,
      cellPadding: 4,
    }
  });
  
  // 5. Footer with Page Numbers
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor('#666666');
    doc.text(
      `Page ${i} of ${pageCount} | MRPL Confidential • Internal Use Only`,
      105,
      285,
      { align: 'center' }
    );
  }
  
  // 6. Save PDF
  doc.save(`MRPL_${reportTitle.replace(/[\s+]/g, '_')}_${today.replace(/\//g, '-')}.pdf`);
};
